-- Replace all 32 official puzzles (mystery/absurd/scifi/crime originals)
-- with rewritten content. Run this whole script in the Supabase SQL editor.
-- Safe to re-run.

begin;

-- 1. Remove the old puzzles for these 4 packs.
--    Cascades to puzzle_translations and puzzle_votes.
--    Fails with a foreign-key error if any of these puzzles is still
--    referenced by an active room's questions/guesses/hints -- if that
--    happens, wait for the room to clear (24h cleanup) and rerun.
delete from puzzles
where pack_id in (
  select id from story_packs where slug in (
    $q$mystery-originals-vol1$q$, $q$absurd-originals-vol1$q$, $q$scifi-originals-vol1$q$, $q$crime-originals-vol1$q$
  )
);

-- 2. Staging table with the new puzzle content.
create temporary table _puzzle_import (
  pack_slug text, category_name text, difficulty text,
  title_nl text, scenario_nl text, solution_nl text, hint_nl text,
  title_en text, scenario_en text, solution_en text, hint_en text
) on commit drop;

insert into _puzzle_import
  (pack_slug, category_name, difficulty, title_nl, scenario_nl, solution_nl, hint_nl, title_en, scenario_en, solution_en, hint_en)
values
  ($q$mystery-originals-vol1$q$, $q$Post$q$, $q$medium$q$, $q$Hetzelfde boek, vijf verschillende afzenders$q$, $q$Een man krijgt binnen een jaar vijf keer exact dezelfde roman toegestuurd, telkens tweedehands, telkens door een andere, voor hem onbekende afzender, en telkens zonder begeleidend briefje.$q$, $q$Hij noemde die roman maanden eerder terloops in een interview over zijn herstel van een moeilijke periode, als het boek dat hem er doorheen had geholpen. Leden van een online lotgenotengroep die het interview zagen, stuurden hem onafhankelijk van elkaar hun eigen exemplaar, zonder te weten dat anderen hetzelfde deden.$q$, $q$Vraag niet wie de afzenders zijn, maar wat ze toevallig allemaal hebben gelezen of gezien.$q$, $q$The Same Book, Five Different Senders$q$, $q$Within a year, a man receives the exact same novel five times in the mail, always secondhand, always from a different sender he doesn't know, and never with a note.$q$, $q$He mentioned the novel in passing in an interview months earlier, about recovering from a hard period in his life, as the book that got him through it. Members of an online support group who saw the interview each sent him their own copy, without knowing anyone else was doing the same.$q$, $q$Don't ask who the senders are — ask what they all happen to have read or seen.$q$),
  ($q$mystery-originals-vol1$q$, $q$Buren$q$, $q$medium$q$, $q$De vuilnisbakken die zichzelf verplaatsten$q$, $q$In een flatgebouw staan elke zondagochtend alle vuilnisbakken al keurig bij de deur van elke bewoner, leeg en schoongespoeld, terwijl niemand toegeeft dat gedaan te hebben en de gemeentelijke ophaaldienst dat zeker niet doet.$q$, $q$Een oudere bewoonster, vroeger jarenlang verpleegkundige met een vaste vroege dienst, is al om vijf uur wakker en kan niet stilzitten. Ze zet de bakken zelf buiten, wacht de ophaaldienst op en plaatst ze daarna schoongespoeld voor elke deur terug, zonder dat ooit te vertellen omdat ze het niets bijzonders vindt.$q$, $q$Wie in dit gebouw is er altijd als eerste wakker?$q$, $q$The Bins That Moved Themselves$q$, $q$In an apartment building, every Sunday morning all the trash bins are already sitting neatly by each resident's door, empty and rinsed out, though no one admits to doing it and the municipal collection service certainly doesn't.$q$, $q$An older resident, a nurse for decades on an early shift, is awake by five and can't sit still. She wheels the bins out herself, waits for collection, and puts them back rinsed at every door afterward, never mentioning it because she doesn't think it's worth bringing up.$q$, $q$Who in this building is always the first one awake?$q$),
  ($q$mystery-originals-vol1$q$, $q$Buren$q$, $q$hard$q$, $q$Verse bloemen in een leeg appartement$q$, $q$Al een half jaar staat de bovenbuurwoning leeg sinds de vorige huurder naar het buitenland verhuisde, maar op de vensterbank, goed zichtbaar vanaf de straat, staan elke week verse bloemen, terwijl niemand de deur ooit open heeft zien gaan.$q$, $q$De makelaar die de woning nog altijd probeert te verkopen, ververst de bloemen voor elke bezichtiging om de plek verkoopklaar te laten ogen. Ze plant haar bezoekjes steeds vlak voor of na de gebruikelijke buurttijden, met de reservesleutel die ze van de vorige eigenaar kreeg.$q$, $q$Wie heeft er baat bij dat een lege woning er niet leeg uitziet?$q$, $q$Fresh Flowers in an Empty Apartment$q$, $q$The upstairs apartment has stood empty for six months since the previous tenant moved abroad, but fresh flowers appear on the windowsill every week, clearly visible from the street, though no one has ever seen the door open.$q$, $q$The estate agent still trying to sell the place refreshes the flowers before every viewing to keep it looking move-in ready. She schedules her visits just outside the building's usual quiet hours, using the spare key she got from the previous owner.$q$, $q$Who benefits from an empty home not looking empty?$q$),
  ($q$mystery-originals-vol1$q$, $q$Openbaar vervoer$q$, $q$medium$q$, $q$De stoel die nooit bezet raakt$q$, $q$In een spitstrein ligt iedere ochtend op precies dezelfde plek een handgeschreven bordje 'gereserveerd', terwijl de conducteur bevestigt dat er nooit officieel iets is gereserveerd en de trein toch overvol zit.$q$, $q$Een vaste reiziger maakte deze rit dertig jaar lang samen met zijn vrouw, tot ze vorig jaar overleed. De conducteur, die hen al die jaren kende, legt elke ochtend voor de man aan boord komt het bordje neer, zodat de plek naast hem leeg blijft zonder dat hij ooit hoeft te vragen waarom.$q$, $q$Vraag je niet af wie de plek claimt, maar voor wie hij leeg blijft.$q$, $q$The Seat That Never Fills Up$q$, $q$Every morning on a packed commuter train, the same seat carries a handwritten 'reserved' sign, though the conductor confirms nothing has ever been officially reserved and the train is standing room only.$q$, $q$A regular passenger made this commute for thirty years with his wife, until she passed away last year. The conductor, who knew them both, sets the sign down every morning before the man boards, so the seat beside him stays empty without him ever having to ask.$q$, $q$Don't ask who's claiming the seat — ask who it's being kept empty for.$q$),
  ($q$mystery-originals-vol1$q$, $q$Nutsvoorzieningen$q$, $q$hard$q$, $q$Water dat 's nachts stroomt in een slapend huis$q$, $q$Bij een gezin registreert de watermeter al maanden een flinke piek in verbruik, elke nacht tussen drie en vier uur, terwijl iedereen dan slaapt en een loodgieter geen enkele lekkage in huis kan vinden.$q$, $q$Onder het gazon zit een oude, professioneel aangelegde beregeningsinstallatie van de vorige eigenaar, nooit gemeld bij de verkoop. Na een stroomstoring is de timer teruggevallen op zijn oorspronkelijke fabrieksschema en sproeit hij midden in de nacht water over een border die er allang niet meer ligt.$q$, $q$Het water verlaat het huis misschien wel, voordat iemand het ooit binnen gebruikt.$q$, $q$Water Running at Night in a Sleeping House$q$, $q$A family's water meter has been logging a sharp spike in usage every night between three and four for months, even though everyone is asleep and a plumber can't find a single leak in the house.$q$, $q$Under the lawn sits an old, professionally installed irrigation system from the previous owner, never disclosed at the sale. After a power outage, the timer reset to its original factory schedule and now waters a flower bed that hasn't existed for years, in the middle of the night.$q$, $q$The water might be leaving the house before anyone ever uses it inside.$q$),
  ($q$mystery-originals-vol1$q$, $q$Verjaardag$q$, $q$hard$q$, $q$Eén bloem op de ruitenwisser, elk jaar opnieuw$q$, $q$Op haar verjaardag vindt een vrouw al meer dan tien jaar telkens één verse bloem onder de ruitenwisser van haar auto, altijd dezelfde soort, altijd weg voordat iemand anders het kan zien, ook nadat ze drie keer is verhuisd.$q$, $q$Haar vader deed dit ieder jaar toen ze nog thuis woonde. Na zijn overlijden zette haar moeder de gewoonte in het geheim voort, kwam via gewone gesprekken telkens haar nieuwe adres te weten, en legt de bloem voor zonsopgang neer op weg naar haar vrijwilligersdienst, zonder ooit de eer op te eisen omdat het altijd zijn gewoonte was.$q$, $q$Wie zou, jaar na jaar, altijd weten waar ze nu woont?$q$, $q$One Flower on the Windshield, Every Year$q$, $q$For more than ten years, a woman has found a single fresh flower tucked under her car's wiper blade on her birthday, always the same kind, always gone before anyone else could see it, even across three different addresses.$q$, $q$Her father did this every year while she still lived at home. After he died, her mother quietly kept the tradition going, learning her daughter's new address each time through ordinary conversation, and leaves the flower before sunrise on her way to a volunteer shift, never taking credit because it was always his habit.$q$, $q$Who would always know, year after year, where she lives now?$q$),
  ($q$mystery-originals-vol1$q$, $q$Dieren$q$, $q$easy$q$, $q$De kat die de deur mijdt$q$, $q$Een huiskat die nog nooit buiten is geweest, weigert elke avond rond zes uur in de buurt van de voordeur te komen, terwijl er in de gang niets anders te zien is dan anders.$q$, $q$De hond van de benedenburen wordt elke avond om zes uur precies langs die deur uitgelaten. De kat ruikt en hoort het dier door de kier onder de deur, ook al krijgt de eigenaar de hond zelf nooit te zien.$q$, $q$Wat kan een kat waarnemen dat een mens door een dichte deur niet opmerkt?$q$, $q$The Cat That Avoids the Door$q$, $q$An indoor cat that has never once been outside refuses to go near the front door every evening around six, even though nothing in the hallway looks any different.$q$, $q$The downstairs neighbor's dog is walked past that door at exactly six every evening. The cat can smell and hear it through the gap under the door, even though its owner never actually sees the dog.$q$, $q$What can a cat notice through a closed door that a person can't?$q$),
  ($q$mystery-originals-vol1$q$, $q$Familie$q$, $q$medium$q$, $q$Twee kinderen bellen op dezelfde avond$q$, $q$Een moeder krijgt op een doordeweekse avond, voor het eerst in maanden, binnen een kwartier een telefoontje van allebei haar kinderen, die in verschillende steden wonen en elkaar die dag niet hebben gesproken.$q$, $q$Die ochtend had de moeder, zonder dat te melden, eindelijk een oude familiefoto geüpload naar een gedeeld familiealbum dat ze al maanden aan het digitaliseren was. Beide kinderen kregen rond dezelfde tijd de meldingsapp-notificatie en belden onafhankelijk van elkaar naar aanleiding van dezelfde foto.$q$, $q$Is er vandaag iets gebeurd dat beide kinderen tegelijk, maar apart van elkaar, hebben gezien?$q$, $q$Two Children Call on the Same Evening$q$, $q$For the first time in months, a mother gets a call from both her children within fifteen minutes of each other on an ordinary weeknight, though they live in different cities and hadn't spoken to each other that day.$q$, $q$That morning, without mentioning it, the mother had finally uploaded an old family photo to a shared album she'd been slowly digitizing for months. Both children got the notification around the same time and called independently, prompted by the same photo.$q$, $q$Did something happen today that both children saw at the same time, but separately from each other?$q$),
  ($q$absurd-originals-vol1$q$, $q$Werk$q$, $q$easy$q$, $q$Vijf minuten dicht, midden op de dag$q$, $q$Een winkelier draait elke dag om klokslag twaalf uur het bordje op 'gesloten', precies vijf minuten, om het dan weer op 'open' te zetten, terwijl de lichten aan blijven en hij de winkel nooit verlaat.$q$, $q$Hij eet op dat moment gewoon zijn boterham achter de toonbank en heeft er een broertje dood aan om klanten naar hem te laten kijken tijdens het kauwen. Meer zit er niet achter.$q$, $q$Waar heeft hij vijf minuten voor nodig, als hij de winkel niet eens verlaat?$q$, $q$Closed for Five Minutes, Right at Noon$q$, $q$Every day at the stroke of noon, a shopkeeper flips his sign to 'closed' for exactly five minutes, then flips it back, while the lights stay on and he never actually leaves the shop.$q$, $q$He's simply eating his sandwich behind the counter and hates the idea of customers watching him chew. That's the whole story.$q$, $q$What does he need five minutes for, if he doesn't even leave the shop?$q$),
  ($q$absurd-originals-vol1$q$, $q$Hobby$q$, $q$medium$q$, $q$Een uur per week in een lege opslagbox$q$, $q$Een man huurt al een jaar een opslagbox aan de andere kant van de stad, waar hij elke zondag precies een uur doorbrengt, zonder ooit iets naar binnen of naar buiten te dragen.$q$, $q$In de box staat een drumstel dat hij thuis nooit zou kunnen spelen zonder de buren gek te maken. De opslaghal ligt ver genoeg van woonhuizen dat niemand klaagt, en het uit- en weer inpakken van het stel zou zijn enige vrije uur opeten, dus laat hij het gewoon staan.$q$, $q$Wat kun je in een afgesloten ruimte doen dat je thuis niet zou kunnen, zonder dat het om spullen gaat?$q$, $q$One Hour a Week in an Empty Storage Unit$q$, $q$For a year, a man has rented a storage unit across town where he spends exactly one hour every Sunday, never carrying anything in or out.$q$, $q$The unit holds a drum kit he could never play at home without driving the neighbors mad. The storage facility is far enough from houses that no one complains, and packing the kit up and back down each week would eat into his one free hour, so he just leaves it there.$q$, $q$What could you do in a locked room that you couldn't do at home, that has nothing to do with belongings?$q$),
  ($q$absurd-originals-vol1$q$, $q$Werk$q$, $q$medium$q$, $q$Nooit een vergadering van precies een half uur$q$, $q$Een projectmanager plant elke vergadering exact negenenveertig minuten, nooit dertig, nooit een uur, en weigert uit te leggen waarom als iemand ernaar vraagt.$q$, $q$Het boekingssysteem voor de vergaderzalen rekent per aangebroken kwartier af, met een afrondingsregel die hij als enige heeft doorgrond: negenenveertig minuten is het langst dat een vergadering kan duren zonder in het duurdere tarief te vallen. Hij bespaart zo elke week een paar euro, en vindt het net te onbenullig om aan zijn team uit te leggen.$q$, $q$Kijk niet naar de klok in de vergaderzaal, maar naar de rekening die erna komt.$q$, $q$Never a Meeting of Exactly Half an Hour$q$, $q$A project manager schedules every meeting for exactly forty-nine minutes, never thirty, never an hour, and refuses to explain why whenever someone asks.$q$, $q$The room-booking system bills by the quarter hour it rounds up to, with a quirk only he ever bothered to work out: forty-nine minutes is the longest a meeting can run without tipping into the pricier bracket. He saves a few euros a week and finds it just a bit too petty to explain to his team.$q$, $q$Don't look at the clock in the meeting room — look at the bill that comes after.$q$),
  ($q$absurd-originals-vol1$q$, $q$Gewoonte$q$, $q$easy$q$, $q$Altijd de neus naar de uitgang$q$, $q$Een vrouw parkeert haar auto altijd met de neus naar de uitgang, op elke parkeerplek die ze ooit heeft gebruikt, zelfs op een doodlopende oprit waar niemand ooit haastig hoeft te vertrekken.$q$, $q$Haar vader werkte jarenlang als meldkamercentralist bij de ambulancedienst en hamerde erop dat een auto die klaarstaat om weg te rijden in een noodgeval seconden kan schelen. De gewoonte is gebleven, ook al is de reden op de achtergrond geraakt.$q$, $q$Denk aan wie haar ooit heeft leren rijden, en in welk beroep die persoon werkte.$q$, $q$Always Nose-Out Toward the Exit$q$, $q$A woman always parks her car nose-out toward the exit, in every spot she's ever used, even in a dead-end driveway where no one would ever need to leave in a hurry.$q$, $q$Her father spent years as a dispatcher for the ambulance service and drilled into her that a car ready to pull away can save precious seconds in an emergency. The habit stuck long after the reason behind it faded into the background.$q$, $q$Think about who taught her to drive, and what that person did for a living.$q$),
  ($q$absurd-originals-vol1$q$, $q$Familie$q$, $q$medium$q$, $q$Regen, elke dag, al een jaar lang$q$, $q$Een man stuurt zijn zus al een jaar lang, elke ochtend om acht uur, exact hetzelfde berichtje: 'nog steeds regen', ook al woont hij ergens waar het amper regent, en zij antwoordt altijd alleen met een duimpje omhoog.$q$, $q$Het begon als een weddenschap met een vriend die hij allang vergeten is, om een jaar lang een compleet nietszeggend berichtje te sturen. Zijn zus vond het na een paar weken zo grappig saai dat ze het duimpje een vast onderdeel van hun ochtend liet worden, en nu stuurt hij het vooral nog voor haar.$q$, $q$Vraag niet waarom hij begon, maar waarom hij nooit is gestopt.$q$, $q$Still Raining, Every Day for a Year$q$, $q$For a year, a man has texted his sister the exact same three words every morning at eight: 'still raining,' even though he lives somewhere it barely rains, and she always just replies with a thumbs-up.$q$, $q$It started as a bet with a friend who forgot about it long ago, to spend a year sending a completely meaningless message. His sister found it so funny and boring after a few weeks that the thumbs-up became a fixed part of their mornings, and now he mostly keeps sending it for her.$q$, $q$Don't ask why he started. Ask why he never stopped.$q$),
  ($q$absurd-originals-vol1$q$, $q$Horeca$q$, $q$medium$q$, $q$Precies een kwartier wachten op hetzelfde gerecht$q$, $q$Een vaste klant in een eettentje bestelt elke dag hetzelfde gerecht, maar vraagt de ober telkens om het exact een kwartier later te brengen, nooit eerder, ook al staat de keuken erom bekend snel te zijn.$q$, $q$Hij moet zijn medicatie voor zijn bloedsuiker precies op tijd innemen bij zijn eerste hap. Zijn eigen agenda is te onvoorspelbaar, maar het kwartier van dit tentje is dat niet, dus bouwde hij zijn routine om de betrouwbaarheid van de keuken heen in plaats van andersom.$q$, $q$Wat moet er voor hem exact op tijd gebeuren, vlak voordat hij eet?$q$, $q$Exactly Fifteen Minutes for the Same Meal$q$, $q$A regular at a small diner orders the same dish every day, but always asks the waiter to bring it exactly fifteen minutes later, never sooner, even though the kitchen is known for being fast.$q$, $q$He needs to take his blood-sugar medication precisely on time with his first bite. His own schedule is too unpredictable, but the diner's fifteen minutes never are, so he built his routine around the kitchen's reliability instead of his own.$q$, $q$What has to happen for him exactly on time, right before he eats?$q$),
  ($q$absurd-originals-vol1$q$, $q$School$q$, $q$easy$q$, $q$De gevonden-voorwerpenbak die elke vrijdag leeg is$q$, $q$Op een school ligt de gevonden-voorwerpenbak op donderdag altijd overvol met truien en broodtrommels, maar elke vrijdagmiddag is hij volledig leeg, zonder dat iemand ooit iets heeft zien weghalen.$q$, $q$Een lerares doorzoekt de bak elke vrijdag tijdens de lunchpauze voor zichzelf als een soort spelletje: ze probeert elk voorwerp uit haar hoofd aan de juiste leerling te koppelen en legt alles zelf terug in de kluisjes, zodat de bak leeg het weekend in gaat.$q$, $q$Wie in de school kent de leerlingen goed genoeg om spullen zonder naamlabel toch terug te bezorgen?$q$, $q$The Lost-and-Found Box That's Empty Every Friday$q$, $q$At a school, the lost-and-found box is always overflowing with sweaters and lunchboxes by Thursday, but it's completely empty every Friday afternoon, though no one has ever seen anyone clear it out.$q$, $q$A teacher goes through it every Friday during her lunch break as a kind of private game: she tries to match each item to the right student from memory and returns everything to their lockers herself, so the box goes into the weekend empty.$q$, $q$Who at the school knows the students well enough to return unlabeled things to the right person?$q$),
  ($q$absurd-originals-vol1$q$, $q$Techniek$q$, $q$hard$q$, $q$Alle straatlantaarns doven tegelijk, tien seconden lang$q$, $q$In een nieuwbouwwijk dimmen elke avond, op een net iets ander tijdstip, alle slimme straatlantaarns tegelijk gedurende exact tien seconden, en de netbeheerder verzekert dat er niets mis is met de stroomvoorziening.$q$, $q$De lantaarns zijn gekoppeld aan een pilotfunctie van de gemeente: zodra een sensor bij de dierenopvang verderop een zwervend dier langs de hoofdweg detecteert, dimmen de lichten kort als stil signaal voor een appgroep van vrijwilligers, zonder sirene of melding aan bewoners. Het tijdstip verschilt gewoon, omdat dieren geen agenda hebben.$q$, $q$Het signaal is niet voor bewoners bedoeld. Voor wie dan wel, en wie of wat activeert het?$q$, $q$Every Streetlight Dims at Once, for Ten Seconds$q$, $q$In a new housing estate, every evening at a slightly different time, all the smart streetlights dim in unison for exactly ten seconds, and the grid operator insists nothing is wrong with the power supply.$q$, $q$The lights are wired into a city pilot program: whenever a sensor at the animal shelter down the road detects a stray near the main road, the lights dim briefly as a silent signal to a volunteer group's app, with no siren and no notice to residents. The timing just varies, because animals don't keep a schedule.$q$, $q$The signal isn't meant for residents. Who is it for, and what triggers it?$q$),
  ($q$scifi-originals-vol1$q$, $q$Communicatie$q$, $q$easy$q$, $q$Drie seconden ruis, aan het begin van elk bericht$q$, $q$Elk bericht dat een ruimtestation naar de aarde stuurt, begint met exact drie seconden ruis, ongeacht wie het opneemt of vanuit welke ruimte aan boord.$q$, $q$De communicatieofficier tikt uit gewoonte altijd twee keer op de microfoon voor hij begint te praten, een tic uit zijn tijd bij een grondstation waar dat nodig was om de zender te wekken. Op het station is dat allang niet meer nodig, maar de gewoonte zit er zo ingesleten in dat niemand er nog naar vraagt.$q$, $q$Ligt het probleem bij de zender, de ontvanger, of bij wie op de knop drukt?$q$, $q$Three Seconds of Static at the Start of Every Message$q$, $q$Every message a space station sends to Earth begins with exactly three seconds of static, no matter who records it or which room aboard it comes from.$q$, $q$The comms officer taps the microphone twice out of habit before he starts talking, a tic left over from his time at a ground station where that was needed to wake the transmitter. It hasn't been necessary on the station in years, but the habit is so ingrained that no one even asks about it anymore.$q$, $q$Is the problem with the transmitter, the receiver, or whoever's pressing the button?$q$),
  ($q$scifi-originals-vol1$q$, $q$Techniek$q$, $q$medium$q$, $q$Koffie die elke week een beetje kouder wordt$q$, $q$Het koffiezetapparaat op een ruimtestation zet de koffie iedere week een fractie kouder, geleidelijk aan, terwijl het apparaat zelf geen storing meldt en de verwarmingselementen bij controle prima werken.$q$, $q$Sinds de ingebruikname van een nieuwe onderzoeksmodule trekt het station op piekmomenten meer stroom, en het koffiezetapparaat deelt een stroomkring met die module. Een steeds kleinere spanningsmarge is precies genoeg om het verwarmingselement iets minder hard te laten werken, week na week, tot een technicus het uiteindelijk niet bij het apparaat maar bij het stroombudget zoekt.$q$, $q$Is het probleem van het apparaat zelf, of van wat het apparaat moet delen met de rest van het station?$q$, $q$Coffee That Gets a Little Colder Every Week$q$, $q$The coffee machine on a space station has been brewing coffee a fraction colder every week, gradually, even though the machine reports no fault and the heating element checks out fine.$q$, $q$Since a new research module came online, the station draws more power during peak hours, and the coffee machine shares a circuit with it. A shrinking voltage margin is just enough to make the heating element work a little less hard each week, until an engineer finally traces it not to the machine but to the power budget.$q$, $q$Is the problem with the machine itself, or with what it has to share with the rest of the station?$q$),
  ($q$scifi-originals-vol1$q$, $q$Astronomie$q$, $q$medium$q$, $q$Een ster die knippert in een verdacht regelmatig patroon$q$, $q$Sterrenkundigen zien de helderheid van een verre ster in een opvallend regelmatig ritme flikkeren, genoeg om even te hopen op een buitenaards signaal, tot het patroon wordt nagetrokken.$q$, $q$Een nieuw onderhoudsrobotje op de steunarm van de telescoop passeert tijdens zijn vaste schoonmaakroute periodiek een deel van de opening, en onderbreekt daarbij vanuit precies die hoek steeds even het sterlicht. Het signaal kwam niet van de ster, maar van het observatorium zelf.$q$, $q$Kijk niet verder de ruimte in, maar dichterbij: staat er iets tussen de telescoop en de ster?$q$, $q$A Star Flickering in a Suspiciously Regular Pattern$q$, $q$Astronomers spot a distant star's brightness flickering in a strikingly regular rhythm, enough to briefly hope for an alien signal, until the pattern is traced back.$q$, $q$A newly installed maintenance drone on the telescope's own support arm periodically crosses part of the aperture during its scheduled cleaning route, briefly blocking the starlight from that exact angle each time. The 'signal' didn't come from the star — it came from the observatory itself.$q$, $q$Don't look further into space. Look closer: is something sitting between the telescope and the star?$q$),
  ($q$scifi-originals-vol1$q$, $q$Bemanning$q$, $q$easy$q$, $q$Ze antwoordt voor haar naam wordt genoemd$q$, $q$Bij de dagelijkse hoofdtelling aan boord zegt een bemanningslid steevast al 'aanwezig' voor haar naam eigenlijk wordt afgeroepen, twee volle seconden te vroeg, elke dag opnieuw.$q$, $q$Ze kent de volgorde van de hoofdtelling na jaren dienst uit haar hoofd en weet precies wanneer haar naam eraan komt. Ze antwoordt gewoon iets te vroeg uit pure gewoonte, niet omdat er iets vreemds aan de hand is.$q$, $q$Hoe lang doet ze deze hoofdtelling al, en wat zou dat met haar reactietijd doen?$q$, $q$She Answers Before Her Name Is Called$q$, $q$At the daily roll call aboard the station, one crew member always says 'present' a full two seconds before her name is actually called, every single day.$q$, $q$After years of service she knows the roll-call order by heart and knows exactly when her name is coming. She just answers a beat early out of sheer habit — there's nothing stranger to it than that.$q$, $q$How long has she been doing this roll call, and what would that do to her timing?$q$),
  ($q$scifi-originals-vol1$q$, $q$Techniek$q$, $q$hard$q$, $q$Een sonde meldt zich, twee jaar later, vanaf de verkeerde plek$q$, $q$Een verkenningssonde werd na een zware zonnestorm als verloren beschouwd toen het contact wegviel. Twee jaar later stuurt hij plots weer feilloze data, maar niet vanaf het traject waarop hij voor het laatst is gevolgd, vanaf een volledig andere, nooit voorspelde koers.$q$, $q$De storm beschadigde tijdelijk de primaire navigatiechip, waardoor de sonde twee jaar lang ongecorrigeerd is afgedreven op de noodstroom van zijn reservesystemen. Pas toen de zonnepanelen na al die tijd genoeg lading hadden opgebouwd voor een volledige herstart, kwamen navigatie en communicatie weer online, op een positie die intussen ver van de oude voorspelling lag.$q$, $q$De sonde loog niet over zijn positie. De oude voorspelling gold gewoon niet meer na de storm.$q$, $q$A Probe Checks In, Two Years Later, From the Wrong Place$q$, $q$A survey probe was declared lost after contact dropped during a severe solar storm. Two years later it suddenly transmits flawless data again, but not from the trajectory it was last tracked on — from a completely different course, never predicted.$q$, $q$The storm temporarily fried its primary navigation chip, leaving the probe drifting uncorrected for two years on backup power. Only once its solar panels had built up enough charge over that time for a full reboot did navigation and comms come back online, from a position that had long since drifted from the old prediction.$q$, $q$The probe wasn't lying about its position. The old prediction simply stopped holding after the storm.$q$),
  ($q$scifi-originals-vol1$q$, $q$Techniek$q$, $q$hard$q$, $q$Twee identieke luiken, twee heel verschillende krachten nodig$q$, $q$Aan weerszijden van een ruimtestation zitten twee identieke airlocks, altijd samen onderhouden en getest. Toch kost het opeens duidelijk meer kracht om de ene open te krijgen dan de andere, terwijl monteurs geen enkel mechanisch mankement vinden.$q$, $q$De stroeve airlock ligt al maandenlang, door de huidige stand van de baan, voortdurend in fel, ongefilterd zonlicht, terwijl de andere in de schaduw van het station blijft. Het metalen kozijn aan de zonzijde is door de warmte een fractie uitgezet, precies genoeg om extra wrijving te geven, terwijl het kozijn aan de schaduwzijde op temperatuur is gebleven.$q$, $q$Vraag niet wat er stuk is, maar welke kant van het station meer zon krijgt dan de andere.$q$, $q$Two Identical Hatches, Two Very Different Amounts of Force$q$, $q$A space station has two identical airlocks on opposite sides, always serviced and tested together. Yet one has suddenly become noticeably harder to open than the other, though engineers find no mechanical fault in either.$q$, $q$Given the station's current orbital phase, the stiff airlock has spent months sitting in constant, unfiltered sunlight, while the other stays in the station's shadow. The metal frame on the sunlit side has expanded a fraction from the heat, just enough to add friction, while the shaded frame has stayed at normal temperature.$q$, $q$Don't ask what's broken. Ask which side of the station gets more sun than the other.$q$),
  ($q$scifi-originals-vol1$q$, $q$Voorraad$q$, $q$medium$q$, $q$Elke week precies één eiwitreep te weinig$q$, $q$Bij de wekelijkse voorraadtelling in een afgesloten opslagkast mist er steevast precies één eiwitreep, terwijl het slimme slot nooit is geforceerd en maar twee bemanningsleden de toegangscode kennen.$q$, $q$Het nieuwste bemanningslid vindt haar rantsoen te krap voor haar trainingsschema en pakt stilletjes wekelijks één extra reep, maar vult de kast de week erna telkens weer aan vanuit haar eigen persoonlijke voorraad, uit gêne om het gewoon te vragen. Op elk afzonderlijk telmoment lijkt er dus precies één te ontbreken, ook al klopt het over twee weken gerekend weer.$q$, $q$Is de reep echt weg, of ligt het probleem in wanneer er precies wordt geteld?$q$, $q$Exactly One Protein Bar Short, Every Week$q$, $q$The weekly inventory count in a locked storage closet always turns up exactly one protein bar short, though the smart lock has never been forced and only two crew members know the access code.$q$, $q$The newest crew member finds her ration too tight for her training schedule and quietly takes one extra bar each week, but restocks the closet the following week from her own personal supply, too embarrassed to just ask. At any single count it looks like exactly one is missing, even though it evens out over two weeks.$q$, $q$Is the bar actually gone, or does the problem lie in exactly when the counting happens?$q$),
  ($q$scifi-originals-vol1$q$, $q$Communicatie$q$, $q$medium$q$, $q$Berichten voor iemand die niemand aan boord kent$q$, $q$Een bemanningslid krijgt een week lang privéberichten op zijn kajuitterminal die duidelijk voor iemand anders bedoeld zijn, ondertekend met een naam die niemand aan boord herkent, vol details over stationsroddels, tot ze plots stoppen.$q$, $q$Een tijdelijke onderhoudsmonteur had voor haar vertrek haar terminal-ID gekoppeld aan een doorstuurregel naar haar grondaccount. Toen die ID later werd hergebruikt voor dit bemanningslid, bleef de oude doorstuurregel per ongeluk actief, tot een beheerder bij een routinecontrole de accountlijst opschoonde.$q$, $q$Is deze terminal-ID er altijd al geweest, of heeft hij ooit een andere eigenaar gehad?$q$, $q$Messages for Someone No One Aboard Knows$q$, $q$For a week, a crew member receives private messages on his cabin terminal clearly meant for someone else, signed with a name no one aboard recognizes, full of detailed station gossip, until they suddenly stop.$q$, $q$A temporary maintenance contractor had linked her terminal ID to a forwarding rule pointing at her ground account before she left. When that ID was later reassigned to this crew member, the old forwarding rule stayed active by accident, until an administrator cleaned up the account list during a routine check.$q$, $q$Has this terminal ID always belonged to him, or did it once have another owner?$q$),
  ($q$crime-originals-vol1$q$, $q$Interne diefstal$q$, $q$medium$q$, $q$Precies hetzelfde tekort, elke donderdag$q$, $q$Bij een kleine boekwinkel klopt de kassa aan het eind van de dag nooit helemaal, maar alleen op donderdag, en altijd met exact hetzelfde kleine bedrag, terwijl de ochtendtelling die dag steeds gewoon klopt.$q$, $q$Een parttime medewerker die alleen op donderdag werkt, trakteert zichzelf steevast op een koffie van het kleine hoekje met versnaperingen zonder die netjes aan te slaan, telkens van plan het later zelf bij te leggen, en telkens vergeten voor de volgende dienst. Het bedrag is te klein om hem ooit te laten denken dat het ertoe doet.$q$, $q$Waarom juist die ene dag, en wie werkt er alleen op die dag?$q$, $q$The Exact Same Shortfall, Every Thursday$q$, $q$At a small bookshop, the till never quite adds up at closing — but only on Thursdays, and always by the exact same small amount, even though the morning count that day is always correct.$q$, $q$A part-time employee who only works Thursdays treats himself to a coffee from the shop's small snack corner without ringing it up properly, always meaning to cover it out of his own pocket later, and always forgetting by his next shift. The amount is too small for him to ever think it matters.$q$, $q$Why that one day specifically, and who only works that day?$q$),
  ($q$crime-originals-vol1$q$, $q$Vervalsing$q$, $q$hard$q$, $q$Een handtekening, drie dagen na zijn overlijden$q$, $q$Een goed doel ontvangt al tien jaar ieder jaar dezelfde donatiebrief van een welgestelde schenker, steeds met een identieke, sierlijke handtekening. Dit jaar blijkt de brief drie dagen na zijn bevestigde overlijdensdatum te zijn verstuurd.$q$, $q$De schenker liet, wetend dat zijn gezondheid achteruitging, jaren geleden samen met zijn advocaat een hele reeks brieven vooraf ondertekenen en dateren, om automatisch elk jaar te worden verstuurd, ongeacht zijn gezondheid. Zo zou de financiering van het goede doel nooit merkbaar stokken, zelfs niet in het jaar dat hij stierf. De handtekening was echt, alleen jaren ouder dan de postdatum deed vermoeden.$q$, $q$Is de handtekening vals, of is alleen het moment van versturen later dan je zou verwachten?$q$, $q$A Signature, Three Days After His Death$q$, $q$A charity has received the same donation letter every year for a decade from a wealthy donor, always with an identical, elegant signature. This year, the letter turns out to have been sent three days after his confirmed date of death.$q$, $q$Knowing his health was failing, the donor had a lawyer help him pre-sign and date an entire batch of letters years in advance, set to be mailed automatically every year regardless of his health, so the charity's funding would never visibly interrupt — not even in the year he died. The signature was real; it was just years older than the postmark suggested.$q$, $q$Is the signature fake, or is it just the timing of the mailing that's later than you'd expect?$q$),
  ($q$crime-originals-vol1$q$, $q$Vals spoor$q$, $q$medium$q$, $q$Geen slot geforceerd, toch ingebroken$q$, $q$Een inbraakslachtoffer is stellig: de dief moet een sleutel hebben gehad, want er is geen slot geforceerd. Toch bezweert de slotenmaker die het huis vorige maand heeft omgezet, dat hij alleen aan de bewoner zelf een sleutel heeft afgegeven.$q$, $q$De tienerzoon van de bewoner had maanden eerder, zonder het te zeggen, zelf een reservesleutel laten bijmaken bij een bouwmarkt en die verloren op een feestje, aan een sleutelhanger met een onvoorzichtig bevestigd labeltje met het huisadres erop. Wie de sleutel oppikte, wist zo precies welke deur hij opende.$q$, $q$De slotenmaker gaf maar één sleutel af. Is er sindsdien nog een tweede bijgekomen, buiten hem om?$q$, $q$No Lock Forced, Yet Someone Broke In$q$, $q$A burglary victim is certain the thief must have had a key, since there's no sign of forced entry. Yet the locksmith who rekeyed the house last month swears he handed a key to no one but the homeowner.$q$, $q$The homeowner's teenage son had quietly had a spare key cut at a hardware store months earlier and lost it at a party, on a keyring with a carelessly attached tag showing the house address. Whoever picked it up knew exactly which door it opened.$q$, $q$The locksmith only handed over one key. Has a second one appeared since, without him knowing?$q$),
  ($q$crime-originals-vol1$q$, $q$Fraude$q$, $q$hard$q$, $q$Jarenlang dezelfde ronde bedragen voor 'kantoorbenodigdheden'$q$, $q$Een kleine ondernemer wordt verdacht van fiscale fraude nadat controleurs jarenlang verdacht ronde, bijna identieke uitgaven voor 'kantoorbenodigdheden' vinden, terwijl hij zweert het merendeel van die facturen nooit zelf te hebben ingediend.$q$, $q$Zijn boekhouder verduisterde al jaren geld bij meerdere kleine klanten tegelijk, door bij elk van hen de post kantoorbenodigdheden maandelijks met een bescheiden, moeilijk opvallend bedrag op te hogen en het verschil via een tussenrekening naar zichzelf door te sluizen. Pas toen een nieuwe controleur meerdere klanten van dezelfde boekhouder naast elkaar legde, viel het identieke patroon over compleet losstaande bedrijven op.$q$, $q$Kijk niet naar één bedrijf, maar naar wie de boekhouding van meerdere bedrijven tegelijk doet.$q$, $q$The Same Round Numbers for 'Office Supplies,' Year After Year$q$, $q$A small business owner is suspected of tax fraud after auditors find years of suspiciously round, near-identical expenses for 'office supplies,' though he swears he never filed most of those invoices himself.$q$, $q$His bookkeeper had been embezzling from several small clients at once for years, padding each one's office-supplies line by a modest, easy-to-miss amount every month and routing the difference to himself through an intermediary account. It only surfaced when a new auditor compared several of the bookkeeper's clients side by side and noticed the identical pattern running across otherwise unrelated businesses.$q$, $q$Don't look at just one business. Look at who handles the books for several at once.$q$),
  ($q$crime-originals-vol1$q$, $q$Beveiligingsfraude$q$, $q$hard$q$, $q$Elf minuten herhaalde beelden, elke nacht op een ander moment$q$, $q$De beveiligingscamera's van een magazijn leveren al maanden feilloze nachtbeelden, tot onderzoekers ontdekken dat elke nacht, op een steeds ander tijdstip, elf minuten lang gewoon de beelden van de vorige nacht worden afgespeeld in plaats van live beeld.$q$, $q$De nachtwaker bezorgt tijdens de rustige uren van zijn dienst stiekem eten via een bezorgapp en had het systeem maanden geleden zo ingesteld dat het elke keer een schoon fragment van elf minuten herhaalt terwijl hij weg is. Het tijdstip verschilt steeds omdat zijn bezorgopdrachten onvoorspelbaar binnenkomen. Het was nooit bedoeld om diefstal te dekken, alleen zijn bijbaantje, tot een routinecontrole van de metadata het aan het licht bracht.$q$, $q$Is het gat in de bewaking gepland rond een misdaad, of rond iets anders wat de bewaker die avond doet?$q$, $q$Eleven Minutes of Looped Footage, at a Different Time Each Night$q$, $q$A warehouse's security cameras have recorded flawless footage every night for months, until investigators discover that every night, at a different time, eleven minutes of the previous night's footage quietly loops in place of the live feed.$q$, $q$The night guard has been secretly delivering food through a gig app during the quiet hours of his shift, and set the system up months ago to loop a clean eleven-minute clip whenever he steps out. The timing varies because his delivery orders come in unpredictably. It was never meant to cover up a theft, just his side job, until a routine metadata check exposed it.$q$, $q$Is the gap in coverage planned around a crime, or around something else the guard does that night?$q$),
  ($q$crime-originals-vol1$q$, $q$Smokkel$q$, $q$hard$q$, $q$Veertig kilo te zwaar, twee jaar lang genegeerd$q$, $q$Een bepaalde vrachtcontainer wordt al twee jaar zonder problemen ingeklaard op dezelfde route, maar weegt bij aankomst steevast veertig kilo meer dan op de vrachtbrief staat, terwijl de zegels nooit sporen van geknoei vertonen en er zichtbaar niets is toegevoegd.$q$, $q$De koelinstallatie van de container, speciaal aangepast voor deze route, heeft een valse bodem in het koelmiddelreservoir waarin de exporteur een dicht, houdbaar goed verpakt in een inerte gel smokkelt. Het gewichtsverschil werd twee jaar lang afgedaan als een bekende afwijking van de weegschaal van die ene container, tot een nieuwe controleur genoeg had van die uitleg en de container liet demonteren.$q$, $q$Zoek niet in de lading zelf, maar in wat er standaard al in de container zit en nooit wordt gecontroleerd.$q$, $q$Forty Kilos Too Heavy, Ignored for Two Years$q$, $q$A specific shipping container has cleared customs without issue on the same route for two years, yet it consistently arrives forty kilos heavier than its manifest states, though the seals never show tampering and nothing visibly has been added.$q$, $q$The container's refrigeration unit, custom-fitted for this route, hides a false bottom in its coolant reservoir where the exporter smuggles a dense, non-perishable good sealed in an inert gel. For two years the discrepancy was written off as a known quirk in that particular container's scale reading, until a new inspector got tired of the excuse and had it taken apart.$q$, $q$Don't search the cargo itself. Look at what's already built into the container and never gets checked.$q$),
  ($q$crime-originals-vol1$q$, $q$Fraude$q$, $q$medium$q$, $q$De storting klopt nooit helemaal$q$, $q$Een cafébaas telt en verpakt elke week zelf precies het juiste bedrag aan contant geld voor de bankstorting, maar op zijn rekening komt telkens een bedrag binnen dat naar beneden is afgerond op een heel tientje.$q$, $q$De baliemedewerker die zijn storting al jaren verwerkt, steekt bij elke transactie het kleine resterende wisselgeld zelf in eigen zak, ervan uitgaand dat een ondernemer met vaste, regelmatige stortingen een verschil van een paar euro nooit zou opmerken of de moeite van melden waard vindt. Pas na een belastingcontrole, waarbij hij voor het eerst zelf alles nauwkeurig bijhoudt, valt het patroon hem op.$q$, $q$Is het verschil bij hem ontstaan, voordat hij is gaan tellen, of erna, bij wie het geld ontvangt?$q$, $q$The Deposit Never Quite Adds Up$q$, $q$A café owner counts and bags the exact right amount of cash for his weekly bank deposit himself, yet the amount that lands in his account is always rounded down to the nearest ten.$q$, $q$The teller who has processed his deposits for years pockets the small leftover change each time, assuming a business owner making regular deposits would never notice or bother reporting a few euros' difference. He only catches the pattern after a tax audit forces him to start keeping his own precise log.$q$, $q$Did the difference happen before he counted the money, or after, at the hands of whoever receives it?$q$),
  ($q$crime-originals-vol1$q$, $q$Vals spoor$q$, $q$medium$q$, $q$De vluchtauto staat precies waar de camera's niets zien$q$, $q$Na een overval wordt de vluchtauto teruggevonden precies op de plek waar de verkeerscamera's een blinde vlek hebben. Rechercheurs snappen er niets van: elke route naar die plek had minstens één werkende camera moeten passeren, maar geen enkele registreert een overeenkomstig voertuig.$q$, $q$De dief reed zijn eigen vluchtauto daar helemaal niet naartoe. Hij huurde via een deelautodienst een identiek model, reed via achterafwegen zonder camera's naar de blinde vlek, en liep het laatste stukje om over te stappen op zijn echte auto, die een tegen contant geld ingehuurde chauffeur, die van niets wist, uren eerder al doodgewoon als 'gewone huurauto-inlevering' had geparkeerd.$q$, $q$Zoek niet naar de auto die de dief zelf bestuurde op weg naar de blinde vlek. Reed hij daar wel echt naartoe?$q$, $q$The Getaway Car Sits Exactly Where the Cameras Can't See$q$, $q$After a robbery, the getaway car turns up exactly where the traffic cameras have a blind spot. Investigators are stumped: every route to that spot should have passed at least one working camera, yet none logged a matching vehicle.$q$, $q$The thief never drove his own getaway car there at all. He rented an identical model through a car-sharing app, took camera-free back roads to the blind spot, and walked the last stretch to switch into his real car — which a cash-paid driver, who knew nothing, had already parked there hours earlier as an ordinary rental drop-off.$q$, $q$Don't look for the car the thief himself drove to the blind spot. Did he actually drive there at all?$q$);

-- 3. Make sure every referenced category already exists (matched
--    case-insensitively on its Dutch name, same as the app's import path).
do $$
declare
  r record;
  v_category_id uuid;
begin
  for r in select distinct category_name from _puzzle_import loop
    select category_id into v_category_id
      from category_translations
      where locale = 'nl' and name ilike r.category_name
      limit 1;

    if v_category_id is null then
      insert into categories default values returning id into v_category_id;
      insert into category_translations (category_id, locale, name, status)
        values (v_category_id, 'nl', r.category_name, 'reviewed');
    end if;
  end loop;
end $$;

-- 4. Insert each puzzle plus its nl/en translations.
do $$
declare
  r record;
  v_pack_id uuid;
  v_category_id uuid;
  v_puzzle_id uuid;
begin
  for r in select * from _puzzle_import loop
    select id into v_pack_id from story_packs where slug = r.pack_slug;
    select category_id into v_category_id
      from category_translations
      where locale = 'nl' and name ilike r.category_name
      limit 1;

    insert into puzzles (pack_id, category_id, difficulty)
      values (v_pack_id, v_category_id, r.difficulty)
      returning id into v_puzzle_id;

    insert into puzzle_translations (puzzle_id, locale, title, scenario, solution, hint, status)
      values (v_puzzle_id, 'nl', r.title_nl, r.scenario_nl, r.solution_nl, r.hint_nl, 'reviewed');
    insert into puzzle_translations (puzzle_id, locale, title, scenario, solution, hint, status)
      values (v_puzzle_id, 'en', r.title_en, r.scenario_en, r.solution_en, r.hint_en, 'reviewed');
  end loop;
end $$;

commit;
